### ISSUE TITLE
Pre-Compilation error with tx_enable_pin: GPIO

### ISSUE THREAD

**Issue by schmutzgeier** [MSkjel/esphome-flexit-modbus-server#1]
`tx_enable_pin: GPIOX`

causes an error for me pre-compilation.

>   File "/esphome/esphome/cpp_generator.py", line 381, in safe_exp
    raise ValueError("Object is not an expression", obj)
ValueError: ('Object is not an expression', {'number': 4, 'mode': {'output': True, 'input': False, 'open_drain': False, 'pullup': False, 'pulldown': False}, 'id': ID<esp32_esp32internalgpiopin_id_3 declaration=True, type=esp32::ESP32InternalGPIOPin, manual=False>, 'inverted': False, 'ignore_pin_validation_error': False, 'ignore_strapping_warning': False, 'drive_strength': 20.0})

YAML
```
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:
  baud_rate: 115200
  hardware_uart: UART1

external_components:
  - source: github://MSkjel/esphome-flexit-modbus-server@main
    refresh: 60s
    components: 
      - flexit_modbus_server

uart:
  id: modbus_uart
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 115200


flexit_modbus_server:
  - id: server
    uart_id: modbus_uart
    address: 3
    # Optional settings
    tx_enable_pin: GPIO4
```

esphome 2025.3.2

Maybe the issue was introduded with one of the recent esphome updates?

I have tried different GPIOs
